from app.models import OrderIntention, Side, OrderType, Status, TimeInForce

MOCK_ORDERS = [
    # ISS-006 - więcej zamówień (15 zamówień)
    OrderIntention(
        id="ORD-001",
        newIssueId="ISS-006",
        symbol="AAPL",
        side=Side.BUY,
        quantity=100,
        price=175.50,
        orderType=OrderType.LIMIT,
        status=Status.PENDING,
        timeInForce=TimeInForce.DAY,
        createdAt="2024-01-15 10:30:00",
        traderId="TRD-001",
        account="ACC-001",
        strategy="Momentum"
    ),
    OrderIntention(
        id="ORD-002",
        newIssueId="ISS-006",
        symbol="MSFT",
        side=Side.SELL,
        quantity=50,
        price=330.25,
        orderType=OrderType.MARKET,
        status=Status.FILLED,
        timeInForce=TimeInForce.IOC,
        createdAt="2024-01-15 11:15:00",
        traderId="TRD-002",
        account="ACC-002",
        strategy="Mean Reversion"
    ),
    OrderIntention(
        id="ORD-003",
        newIssueId="ISS-006",
        symbol="GOOGL",
        side=Side.BUY,
        quantity=75,
        price=135.80,
        orderType=OrderType.LIMIT,
        status=Status.PENDING,
        timeInForce=TimeInForce.GTC,
        createdAt="2024-01-15 09:45:00",
        traderId="TRD-001",
        account="ACC-001",
        strategy="Trend Following"
    ),
    OrderIntention(
        id="ORD-004",
        newIssueId="ISS-006",
        symbol="TSLA",
        side=Side.SELL,
        quantity=120,
        price=225.40,
        orderType=OrderType.LIMIT,
        status=Status.FILLED,
        timeInForce=TimeInForce.DAY,
        createdAt="2024-01-15 14:20:00",
        traderId="TRD-003",
        account="ACC-003",
        strategy="Swing Trading"
    ),
    OrderIntention(
        id="ORD-005",
        newIssueId="ISS-006",
        symbol="NVDA",
        side=Side.BUY,
        quantity=200,
        price=520.75,
        orderType=OrderType.LIMIT,
        status=Status.FILLED,
        timeInForce=TimeInForce.GTC,
        createdAt="2024-01-15 13:10:00",
        traderId="TRD-004",
        account="ACC-004",
        strategy="AI Trading"
    ),
    OrderIntention(
        id="ORD-006",
        newIssueId="ISS-006",
        symbol="META",
        side=Side.BUY,
        quantity=80,
        price=380.20,
        orderType=OrderType.MARKET,
        status=Status.FILLED,
        timeInForce=TimeInForce.IOC,
        createdAt="2024-01-15 12:45:00",
        traderId="TRD-002",
        account="ACC-002",
        strategy="Social Media Sentiment"
    ),
    OrderIntention(
        id="ORD-007",
        newIssueId="ISS-006",
        symbol="AMZN",
        side=Side.SELL,
        quantity=150,
        price=155.30,
        orderType=OrderType.LIMIT,
        status=Status.PENDING,
        timeInForce=TimeInForce.DAY,
        createdAt="2024-01-15 15:30:00",
        traderId="TRD-001",
        account="ACC-001",
        strategy="E-commerce Focus"
    ),
    OrderIntention(
        id="ORD-008",
        newIssueId="ISS-006",
        symbol="TSLA",
        side=Side.BUY,
        quantity=90,
        price=215.00,
        orderType=OrderType.STOP,
        status=Status.CANCELLED,
        timeInForce=TimeInForce.DAY,
        createdAt="2024-01-15 16:15:00",
        traderId="TRD-003",
        account="ACC-003"
    ),
    OrderIntention(
        id="ORD-009",
        newIssueId="ISS-006",
        symbol="JPM",
        side=Side.SELL,
        quantity=300,
        price=170.45,
        orderType=OrderType.MARKET,
        status=Status.FILLED,
        timeInForce=TimeInForce.IOC,
        createdAt="2024-01-15 11:45:00",
        traderId="TRD-005",
        account="ACC-005",
        strategy="Banking Sector"
    ),
    OrderIntention(
        id="ORD-010",
        newIssueId="ISS-006",
        symbol="GOOGL",
        side=Side.SELL,
        quantity=60,
        price=140.20,
        orderType=OrderType.LIMIT,
        status=Status.FILLED,
        timeInForce=TimeInForce.GTC,
        createdAt="2024-01-15 10:15:00",
        traderId="TRD-002",
        account="ACC-002",
        strategy="Tech Rotation"
    ),
    OrderIntention(
        id="ORD-011",
        newIssueId="ISS-006",
        symbol="AAPL",
        side=Side.SELL,
        quantity=70,
        price=178.90,
        orderType=OrderType.MARKET,
        status=Status.REJECTED,
        timeInForce=TimeInForce.IOC,
        createdAt="2024-01-15 14:50:00",
        traderId="TRD-001",
        account="ACC-001",
        strategy="Profit Taking"
    ),
    OrderIntention(
        id="ORD-012",
        newIssueId="ISS-006",
        symbol="NVDA",
        side=Side.SELL,
        quantity=100,
        price=525.00,
        orderType=OrderType.LIMIT,
        status=Status.PENDING,
        timeInForce=TimeInForce.GTC,
        createdAt="2024-01-15 15:45:00",
        traderId="TRD-004",
        account="ACC-004"
    ),
    OrderIntention(
        id="ORD-013",
        newIssueId="ISS-006",
        symbol="MSFT",
        side=Side.BUY,
        quantity=120,
        price=328.75,
        orderType=OrderType.LIMIT,
        status=Status.FILLED,
        timeInForce=TimeInForce.DAY,
        createdAt="2024-01-15 09:30:00",
        traderId="TRD-002",
        account="ACC-002"
    ),
    OrderIntention(
        id="ORD-014",
        newIssueId="ISS-006",
        symbol="META",
        side=Side.SELL,
        quantity=40,
        price=385.50,
        orderType=OrderType.MARKET,
        status=Status.FILLED,
        timeInForce=TimeInForce.IOC,
        createdAt="2024-01-15 13:45:00",
        traderId="TRD-003",
        account="ACC-003",
        strategy="Quick Flip"
    ),
    OrderIntention(
        id="ORD-015",
        newIssueId="ISS-006",
        symbol="AMZN",
        side=Side.BUY,
        quantity=180,
        price=152.80,
        orderType=OrderType.STOP,
        status=Status.CANCELLED,
        timeInForce=TimeInForce.DAY,
        createdAt="2024-01-15 16:30:00",
        traderId="TRD-005",
        account="ACC-005"
    ),
    
    # ISS-001 - więcej zamówień (12 zamówień)
    OrderIntention(
        id="ORD-101",
        newIssueId="ISS-001",
        symbol="TSLA",
        side=Side.SELL,
        quantity=200,
        price=210.00,
        orderType=OrderType.STOP,
        status=Status.CANCELLED,
        timeInForce=TimeInForce.DAY,
        createdAt="2024-01-14 14:20:00",
        traderId="TRD-003",
        account="ACC-003"
    ),
    OrderIntention(
        id="ORD-102",
        newIssueId="ISS-001",
        symbol="AMZN",
        side=Side.BUY,
        quantity=150,
        price=145.30,
        orderType=OrderType.MARKET,
        status=Status.REJECTED,
        timeInForce=TimeInForce.IOC,
        createdAt="2024-01-14 16:10:00",
        traderId="TRD-002",
        account="ACC-002",
        strategy="Arbitrage"
    ),
    OrderIntention(
        id="ORD-103",
        newIssueId="ISS-001",
        symbol="AAPL",
        side=Side.BUY,
        quantity=250,
        price=172.80,
        orderType=OrderType.LIMIT,
        status=Status.FILLED,
        timeInForce=TimeInForce.GTC,
        createdAt="2024-01-14 10:15:00",
        traderId="TRD-001",
        account="ACC-001",
        strategy="Value Investing"
    ),
    OrderIntention(
        id="ORD-104",
        newIssueId="ISS-001",
        symbol="MSFT",
        side=Side.SELL,
        quantity=180,
        price=335.40,
        orderType=OrderType.MARKET,
        status=Status.FILLED,
        timeInForce=TimeInForce.IOC,
        createdAt="2024-01-14 11:30:00",
        traderId="TRD-004",
        account="ACC-004"
    ),
    OrderIntention(
        id="ORD-105",
        newIssueId="ISS-001",
        symbol="GOOGL",
        side=Side.BUY,
        quantity=95,
        price=138.20,
        orderType=OrderType.LIMIT,
        status=Status.FILLED,
        timeInForce=TimeInForce.DAY,
        createdAt="2024-01-14 13:45:00",
        traderId="TRD-002",
        account="ACC-002",
        strategy="Search Dominance"
    ),
    OrderIntention(
        id="ORD-106",
        newIssueId="ISS-001",
        symbol="NVDA",
        side=Side.SELL,
        quantity=120,
        price=510.25,
        orderType=OrderType.LIMIT,
        status=Status.FILLED,
        timeInForce=TimeInForce.GTC,
        createdAt="2024-01-14 15:20:00",
        traderId="TRD-003",
        account="ACC-003",
        strategy="GPU Market"
    ),
    OrderIntention(
        id="ORD-107",
        newIssueId="ISS-001",
        symbol="META",
        side=Side.BUY,
        quantity=70,
        price=375.80,
        orderType=OrderType.MARKET,
        status=Status.FILLED,
        timeInForce=TimeInForce.IOC,
        createdAt="2024-01-14 12:10:00",
        traderId="TRD-001",
        account="ACC-001"
    ),
    OrderIntention(
        id="ORD-108",
        newIssueId="ISS-001",
        symbol="TSLA",
        side=Side.BUY,
        quantity=110,
        price=208.50,
        orderType=OrderType.LIMIT,
        status=Status.PENDING,
        timeInForce=TimeInForce.DAY,
        createdAt="2024-01-14 16:45:00",
        traderId="TRD-005",
        account="ACC-005",
        strategy="EV Revolution"
    ),
    OrderIntention(
        id="ORD-109",
        newIssueId="ISS-001",
        symbol="JPM",
        side=Side.SELL,
        quantity=220,
        price=168.90,
        orderType=OrderType.MARKET,
        status=Status.REJECTED,
        timeInForce=TimeInForce.IOC,
        createdAt="2024-01-14 14:50:00",
        traderId="TRD-004",
        account="ACC-004",
        strategy="Financials"
    ),
    OrderIntention(
        id="ORD-110",
        newIssueId="ISS-001",
        symbol="AMZN",
        side=Side.SELL,
        quantity=130,
        price=148.75,
        orderType=OrderType.LIMIT,
        status=Status.FILLED,
        timeInForce=TimeInForce.GTC,
        createdAt="2024-01-14 11:15:00",
        traderId="TRD-002",
        account="ACC-002"
    ),
    OrderIntention(
        id="ORD-111",
        newIssueId="ISS-001",
        symbol="AAPL",
        side=Side.SELL,
        quantity=85,
        price=174.20,
        orderType=OrderType.MARKET,
        status=Status.FILLED,
        timeInForce=TimeInForce.IOC,
        createdAt="2024-01-14 15:30:00",
        traderId="TRD-003",
        account="ACC-003",
        strategy="Options Hedging"
    ),
    OrderIntention(
        id="ORD-112",
        newIssueId="ISS-001",
        symbol="MSFT",
        side=Side.BUY,
        quantity=160,
        price=332.80,
        orderType=OrderType.STOP,
        status=Status.CANCELLED,
        timeInForce=TimeInForce.DAY,
        createdAt="2024-01-14 17:00:00",
        traderId="TRD-005",
        account="ACC-005"
    ),
    
    # Dodatkowe newIssueId dla różnorodności
    OrderIntention(
        id="ORD-201",
        newIssueId="ISS-003",
        symbol="BRK.B",
        side=Side.BUY,
        quantity=50,
        price=360.25,
        orderType=OrderType.LIMIT,
        status=Status.PENDING,
        timeInForce=TimeInForce.GTC,
        createdAt="2024-01-16 09:15:00",
        traderId="TRD-001",
        account="ACC-001",
        strategy="Long Term Hold"
    ),
    OrderIntention(
        id="ORD-202",
        newIssueId="ISS-003",
        symbol="V",
        side=Side.SELL,
        quantity=75,
        price=260.40,
        orderType=OrderType.MARKET,
        status=Status.FILLED,
        timeInForce=TimeInForce.IOC,
        createdAt="2024-01-16 10:45:00",
        traderId="TRD-002",
        account="ACC-002",
        strategy="Payment Processing"
    ),
    OrderIntention(
        id="ORD-203",
        newIssueId="ISS-004",
        symbol="DIS",
        side=Side.BUY,
        quantity=120,
        price=92.75,
        orderType=OrderType.LIMIT,
        status=Status.FILLED,
        timeInForce=TimeInForce.DAY,
        createdAt="2024-01-16 13:20:00",
        traderId="TRD-003",
        account="ACC-003",
        strategy="Entertainment"
    ),
    OrderIntention(
        id="ORD-204",
        newIssueId="ISS-005",
        symbol="NFLX",
        side=Side.SELL,
        quantity=90,
        price=480.30,
        orderType=OrderType.MARKET,
        status=Status.PENDING,
        timeInForce=TimeInForce.IOC,
        createdAt="2024-01-16 14:30:00",
        traderId="TRD-004",
        account="ACC-004",
        strategy="Streaming"
    ),
]