from app.models import Issue, IssueStatus, IssuePriority, IssueState, IssueType
from datetime import datetime, timedelta

# Generowanie timestampów z różnymi datami
base_date = datetime.utcnow()
timestamps = [
    (base_date - timedelta(days=i)).isoformat() + "Z"
    for i in range(10)
]

MOCK_ISSUES = [
    Issue(
        id="ISS-001",
        title="Fix order validation for negative quantities",
        status=IssueStatus.OPEN,
        priority=IssuePriority.HIGH,
        type=IssueType.BUG,
        assignee="John Trader",
        createdAt="2024-01-15T10:30:00Z",
        updatedAt="2024-01-15T10:30:00Z",
        state=IssueState.CLOSED,
    ),
    Issue(
        id="ISS-002",
        title="Add dark mode support to blotter",
        status=IssueStatus.IN_PROGRESS,
        priority=IssuePriority.MEDIUM,
        type=IssueType.FEATURE,
        assignee="Sarah Developer",
        createdAt="2024-01-14T14:20:00Z",
        updatedAt="2024-01-16T09:15:00Z",
        state=IssueState.CLOSED,
    ),
    Issue(
        id="ISS-003",
        title="Real-time P&L calculation delay exceeding 500ms",
        status=IssueStatus.OPEN,
        priority=IssuePriority.CRITICAL,
        type=IssueType.BUG,
        assignee="Mike Quant",
        createdAt=timestamps[2],
        updatedAt=timestamps[2],
        state=IssueState.OPEN,
    ),
    Issue(
        id="ISS-004",
        title="Implement trailing stop loss functionality",
        status=IssueStatus.IN_PROGRESS,
        priority=IssuePriority.HIGH,
        type=IssueType.FEATURE,
        assignee="Emma Risk",
        createdAt=timestamps[3],
        updatedAt=timestamps[0],  # Ostatnio zaktualizowane
        state=IssueState.OPEN,
    ),
    Issue(
        id="ISS-005",
        title="Market data feed disconnection during high volatility",
        status=IssueStatus.OPEN,
        priority=IssuePriority.CRITICAL,
        type=IssueType.BUG,
        assignee="David Ops",
        createdAt=timestamps[4],
        updatedAt=timestamps[4],
        state=IssueState.OPEN,
    ),
    Issue(
        id="ISS-006",
        title="Add risk limits validation for block trades",
        status=IssueStatus.OPEN,
        priority=IssuePriority.HIGH,
        type=IssueType.IMPROVEMENT,
        assignee="Emma Risk",
        createdAt=timestamps[5],
        updatedAt=timestamps[5],
        state=IssueState.OPEN,
    ),
    Issue(
        id="ISS-007",
        title="Portfolio summary report generation optimization",
        status=IssueStatus.IN_PROGRESS,
        priority=IssuePriority.MEDIUM,
        type=IssueType.IMPROVEMENT,
        assignee="Sarah Developer",
        createdAt=timestamps[6],
        updatedAt=timestamps[1],
        state=IssueState.OPEN,
    ),
    Issue(
        id="ISS-008",
        title="Fix currency conversion rounding in multi-leg strategies",
        status=IssueStatus.RESOLVED,
        priority=IssuePriority.HIGH,
        type=IssueType.BUG,
        assignee="Mike Quant",
        createdAt=timestamps[7],
        updatedAt=timestamps[0],
        state=IssueState.CLOSED,
    ),
    Issue(
        id="ISS-009",
        title="Create dark pool liquidity indicator widget",
        status=IssueStatus.OPEN,
        priority=IssuePriority.MEDIUM,
        type=IssueType.FEATURE,
        assignee="John Trader",
        createdAt=timestamps[8],
        updatedAt=timestamps[8],
        state=IssueState.OPEN,
    ),
    Issue(
        id="ISS-010",
        title="Update regulatory compliance documentation for MiFID II",
        status=IssueStatus.OPEN,
        priority=IssuePriority.MEDIUM,
        type=IssueType.TASK,
        assignee="Compliance Team",
        createdAt=timestamps[9],
        updatedAt=timestamps[9],
        state=IssueState.OPEN,
    ),
    Issue(
        id="ISS-011",
        title="Fix memory leak in real-time chart component",
        status=IssueStatus.IN_PROGRESS,
        priority=IssuePriority.HIGH,
        type=IssueType.BUG,
        assignee="David Ops",
        createdAt=timestamps[1],
        updatedAt=timestamps[0],
        state=IssueState.OPEN,
    ),
    Issue(
        id="ISS-012",
        title="Add AI-powered trade anomaly detection",
        status=IssueStatus.OPEN,
        priority=IssuePriority.CRITICAL,
        type=IssueType.FEATURE,
        assignee="AI Team",
        createdAt=timestamps[0],
        updatedAt=timestamps[0],
        state=IssueState.OPEN,
    ),
]